### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by cdesch** [mustafaturan/oceanex#3]
@mustafaturan Can you put some sample tests of how you want them structured to test the API? Maybe we can fill out the rest.

**Comment by mustafaturan** [comment]
Hi @cdesch 

There are a few options to add tests but I am a little busy to do so, but I appriciate if you can do, you can choose one of them and then I can review and merge:
1) stubbing requests https://github.com/oarrabi/ex_stub
2) mocking requests mock lib
3) vr cassettes to store requests after first interaction

**Comment by cdesch** [comment]
If you can stub it. I can fill in the blanks. Just new to library
